### PR TITLE
Color

### LINKED ISSUE #3: add color
chad stride looks drab. could use some color maybe?

### PR DESCRIPTION
**Pull request by ginglis13**
added color in a similar way that cmatrix does it using ncurses color attrs

press b for blue, c for cyan, etc.

tested on xterm and it works perfectly, try this out on iterm - I tried and got inconsistent results

also, it's pretty easy to add a check for if a terminal supports the coloring - i can add that too

#3

### CODE REVIEW

**Comment by wtheisen** [comment]
Can we get a screenshot please?

**Comment by ginglis13** [comment]
https://yld.me/w2w @wtheisen @sambattalio

**Comment by wtheisen** [comment]
>not using chadpaste for chadstride

**Comment by ginglis13** [comment]
didn't load on chadpaste lol

**Comment by sambattalio** [comment]
What type of video file is that? Cant view on mobile @pbui please fix yld  me

**Comment by pbui** [comment]
@sambattalio Fix your web browser.... works w/ chrome on Android.

**Comment by wtheisen** [comment]
when viewing videos on chadpaste I think you have to click the broken image and view in another tab

**Comment by ginglis13** [comment]
it was outputting the binary... https://chadpaste.com/?cmx.mp4

**Comment by sambattalio** [comment]
Could you make it a flag? This is really good btw chad

**Comment by ginglis13** [comment]
added the flag. I can work out the logic to run with one specific color after the `getopt` change @sambattalio

**Comment by sambattalio** [comment]
Basically added in arguments fully. Might move it around a little but its basically there @ginglis13

**Comment by ginglis13** [comment]
@sambattalio awesome, later tonight if I find time I'll resolve conflicts on this branch to bring your changes in and make my updates 👍🚀

**Comment by sambattalio** [comment]
🚀 📈

**Comment by sambattalio** [comment]
Nice! I'll review this after I get out of class today.

**Comment by ginglis13** [comment]
ok. i still gotta add some shiz, like `-c <color>` and whatnot.

if i do it when i get home from work it should be done ~10pm est

**Comment by sambattalio** [comment]
Oh aight, just ping me and ill peep it 👀

**Comment by ginglis13** [comment]
@sambattalio eagerly awaiting your review :smile:

**Review by sambattalio — APPROVED** [review]
thanks @ginglis13

**Pull request merged**
